{
  "type": "service_account",
  "project_id": "pulse-f5547",
  "private_key_id": "d2f13b5e7d4dxxxxxx",
  "private_key": "-----BEGIN PRIVATE KEY-----\n[PRIVATE KEY HIDDEN]\n-----END PRIVATE KEY-----\n",
  "client_email": "firebase-adminsdk-xxxxx@pulse-f5547.iam.gserviceaccount.com",
  "client_id": "10xxxxxxxxxxxxx",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-xxxxx%40pulse-f5547.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
